[workspace]
members = [
    "arch/i386/vga",
    "arch/i386/tty",
    "arch/x86_64/vga",
    "arch/x86_64/tty",
    "arch/x86_64/limine",
    "kernel", "arch/x86_64/limine",
]
resolver = "3"

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"
opt-level = 2
