[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
tty = { path = "../arch/i386/tty", version = "0.1.0" }

[target.i686-unknown-linux-gnu.dependencies]
tty = { path = "../arch/i386/tty", version = "0.1.0" }

[lib]
crate-type = ["lib", "staticlib"]