[package]
name = "tty-x86_64"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10.0"
limine = { path = "../limine", version = "0.1.0" }

[lib]
crate-type = ["lib"]

[build-dependencies]
cbindgen = "0.29.2"
