name: Build x86_64 ISO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Update to nightly Rust
        run: rustup override set nightly

      - name: Install dependencies
        run: make packages-ci

      - name: Build with Makefile
        run: make iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v6
        with:
          name: thaunos-x86_64.iso
          path: output/thaunos.iso